# Generated by Django 5.1.15 on 2026-03-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Invoice')),
                ('game_id', models.CharField(max_length=50, verbose_name='ID Game')),
                ('game_server', models.CharField(blank=True, max_length=50, null=True, verbose_name='Server Game')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Harga')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('processing', 'Sedang Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal'), ('expired', 'Kadaluarsa')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('balance', 'Saldo'), ('midtrans', 'Midtrans')], default='midtrans', max_length=20, verbose_name='Metode Pembayaran')),
                ('midtrans_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('midtrans_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='URL Pembayaran')),
                ('payment_details', models.JSONField(blank=True, default=dict, verbose_name='Detail Pembayaran')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='games.gameitem', verbose_name='Item Game')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
