# Generated by Django 5.1.15 on 2026-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Metode')),
                ('code', models.SlugField(unique=True, verbose_name='Kode (contoh: bca, gopay)')),
                ('category', models.CharField(choices=[('bank', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('qris', 'QRIS')], default='bank', max_length=20, verbose_name='Kategori')),
                ('logo', models.ImageField(help_text='Upload logo (format SVG/PNG)', upload_to='payments/', verbose_name='Logo')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
