# Generated by Django 5.1.15 on 2026-03-06 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#667eea', help_text='Warna kategori (contoh: #667eea)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon Font Awesome (contoh: fas fa-newspaper)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Artikel',
                'verbose_name_plural': 'Kategori Artikel',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Game')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/', verbose_name='Icon Game')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='games/banners/', verbose_name='Banner Game')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Gambar Artikel')),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Ringkasan artikel', max_length=300)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, help_text='Judul untuk SEO (opsional)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Deskripsi untuk SEO (opsional)', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='games.articlecategory')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='games.game')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Kategori Game',
                'verbose_name_plural': 'Kategori Game',
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Item')),
                ('amount', models.IntegerField(verbose_name='Jumlah (dalam game)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Harga Diskon')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Item Populer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/items/', verbose_name='Gambar Item')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.gamecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Item Game',
                'verbose_name_plural': 'Item Game',
                'ordering': ['category__game', 'price'],
            },
        ),
    ]
